name: Build and Deploy Docker Image to AWS ECR

on:
  push:
    branches:
      - aws 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1



      - name: Build, Tag, and Push Docker image to ECR
        run: |
          # Build the Docker image
          docker build -t das .

          # Tag the image for ECR
          docker tag das:latest <AWS-ACCOUNT-ID>.dkr.ecr.<YOUR-AWS-REGION>.amazonaws.com/das:latest

          # Push to ECR
          docker push <AWS-ACCOUNT-ID>.dkr.ecr.<YOUR-AWS-REGION>.amazonaws.com/my-flask-app:latest

      - name: Post successful build
        run: echo "Docker image built and pushed to ECR!"