name: Build and Deploy Docker Image to AWS ECR

on:
  push:
    branches:
      - aws 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ECR_REPOSITORY: das
      IMAGE_TAG: ${{ github.sha }}



    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo ${{ github.sha }}
          echo $ECR_REPOSITORY
          echo "$ECR_REPOSITORY"

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Post successful build
        run: echo "Docker image built and pushed to ECR!"

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          # script: |
          #   CONTAINERID=$(docker ps -q --filter "ancestor=$ECR_REPOSITORY")
          #   echo "$CONTAINERID"
          #   echo ${{ github.sha }}
          #   echo ${{ github.sha }}
          #   docker kill  "$CONTAINERID" || true
          #   docker rm "$CONTAINERID" || true
          #   docker pull "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          #   docker run -d -p 3009:3009 "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


          script: |
            echo ${{ github.sha }}
            echo "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
            echo "$ECR_REGISTRY"/"$ECR_REPOSITORY":"$IMAGE_TAG"
            echo $ECR_REPOSITORY
            echo $ECR_REGISTRY
            ECR_REPOSITORY=${{ steps.set-output.outputs.ecr_repository }}
            echo "Deploying from $ECR_REPOSITORY"

            CONTAINERID=$(docker ps -q --filter "ancestor=$ECR_REPOSITORY")
            if [ -n "$CONTAINERID" ]; then
              echo "Stopping and removing container $CONTAINERID"
              docker kill "$CONTAINERID" || true
              docker rm "$CONTAINERID" || true
            else
              echo "No containers found for $ECR_REPOSITORY"
            fi

            docker pull "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
