name: Build and Deploy Docker Image to AWS ECR

on:
  push:
    branches:
      - aws 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: ecr_login
        run: |
          aws --version
          $(aws ecr get-login-password --region <YOUR-AWS-REGION>) | docker login --username AWS --password-stdin <AWS-ACCOUNT-ID>.dkr.ecr.<YOUR-AWS-REGION>.amazonaws.com

      - name: Build, Tag, and Push Docker image to ECR
        run: |
          # Build the Docker image
          docker build -t das .

          # Tag the image for ECR
          docker tag das:latest <AWS-ACCOUNT-ID>.dkr.ecr.<YOUR-AWS-REGION>.amazonaws.com/das:latest

          # Push to ECR
          docker push <AWS-ACCOUNT-ID>.dkr.ecr.<YOUR-AWS-REGION>.amazonaws.com/my-flask-app:latest

      - name: Post successful build
        run: echo "Docker image built and pushed to ECR!"