name: hello-world
on:
  push:
    branches:
      - aws 
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "${{secrets.AWS_REGIONT}}"
      - name: my-step2
        run: echo "yo"